begin;
create extension if not exists pgtap with schema extensions;
set local search_path=public,extensions;
select no_plan();
select ok(not has_function_privilege('authenticated','public.service_configure_email_alert_scheduler(text,text,boolean)','execute'),'Authenticated users cannot provision scheduler credentials');
select ok(not has_function_privilege('anon','public.service_set_email_alert_delivery_enabled(boolean)','execute'),'Anonymous callers cannot activate mail');
select ok(not has_function_privilege('service_role','private.dispatch_machine_email_alerts()','execute'),'Only scheduled database owner runs private clock');
select throws_ok($$select public.service_set_email_alert_delivery_enabled(true)$$,'22023',null,'Cannot activate an unconfigured sender');
select throws_ok($$select public.service_configure_email_alert_scheduler('https://attacker.example/functions/v1/email-alert-dispatch',repeat('x',48),false)$$,'22023',null,'Reject arbitrary endpoint origins');
select throws_ok($$select public.service_configure_email_alert_scheduler('https://abcdefghijklmnopqrst.supabase.co/functions/v1/email-alert-dispatch?extra=1',repeat('x',48),false)$$,'22023',null,'Require exact canonical endpoint path');
select throws_ok($$select public.service_configure_email_alert_scheduler('https://abcdefghijklmnopqrst.supabase.co/functions/v1/email-alert-dispatch','weak',false)$$,'22023',null,'Reject short secret');
select lives_ok($$select public.service_configure_email_alert_scheduler('https://abcdefghijklmnopqrst.supabase.co/functions/v1/email-alert-dispatch',repeat('x',48))$$,'Configuring defaults to paused');
select is((public.service_email_alert_delivery_status()->>'deliveryEnabled')::boolean,false,'Configuration does not enable delivery');
select is((public.service_email_alert_delivery_status()->>'ownershipActivated')::boolean,false,'Configuration does not seize legacy ownership');
select is((select active from cron.job where jobname='email-alert-dispatch-v1'),false,'Cron remains inactive');
select is((select command from cron.job where jobname='email-alert-dispatch-v1'),'select private.dispatch_machine_email_alerts();','Scheduled text contains neither credential nor destination');
select is((select count(*)::int from vault.secrets where name in ('email_alert_scheduler_url','email_alert_scheduler_secret')),2,'Dedicated Vault records created');
select is((select last_request_id from private.email_alert_delivery_settings),null,'Configuration dispatches no network requests');
select lives_ok($$select public.service_configure_email_alert_scheduler('https://abcdefghijklmnopqrst.supabase.co/functions/v1/email-alert-dispatch',repeat('y',48),false)$$,'Configuration rotates dedicated secret without duplicate rows');
select is((select count(*)::int from vault.secrets where name in ('email_alert_scheduler_url','email_alert_scheduler_secret')),2,'Rotation updates original Vault records');
select lives_ok($$select public.service_set_email_alert_delivery_enabled(true)$$,'Explicit activation enables verified clock');
select is((public.service_email_alert_delivery_status()->>'ownershipActivated')::boolean,true,'First activation records ownership');
select is((select active from cron.job where jobname='email-alert-dispatch-v1'),true,'Activation enables five-minute clock');
select lives_ok($$select public.service_set_email_alert_delivery_enabled(false)$$,'Explicit pause disables clock');
select is((select active from cron.job where jobname='email-alert-dispatch-v1'),false,'Paused clock inactive');
select is((public.service_email_alert_delivery_status()->>'ownershipActivated')::boolean,true,'Pause preserves ownership');
select is((public.service_begin_next_refund_manager_digest()->>'reason'),'personal_alert_sender_owns_daily','Pausing cannot revive legacy daily sender');
select is((select last_request_id from private.email_alert_delivery_settings),null,'Activation and pause within test transaction never send');
select * from finish();
rollback;
