// Refund-only copy: the portal language preference has a different audience.
export type RefundCustomerLocale = 'en' | 'es';
export const refundSpanishCopy = {
  'We couldn’t open a fresh update. Your saved response is unchanged. Try again, or use the latest Bloomjoy email for help with this same request.': 'No pudimos abrir una actualización. Su respuesta guardada no cambió. Inténtelo de nuevo o use el último correo de Bloomjoy para recibir ayuda con esta misma solicitud.',
  'Choose an answer for each requested detail. You can choose “Not sure / can’t provide” without guessing.': 'Elija una respuesta para cada detalle solicitado. Puede elegir “No lo sé / No lo tengo” sin adivinar.',
  'Choose a saved detail to update or confirm. Your earlier answers are already saved.': 'Elija un dato guardado para corregirlo o confirmarlo. Sus respuestas anteriores ya están guardadas.',
  'We couldn’t save this response. Your answers are still here. Try again, or reply to your Bloomjoy email for help with this same request.': 'No pudimos guardar la respuesta. Sus respuestas siguen aquí. Inténtelo de nuevo o responda al correo de Bloomjoy para obtener ayuda con esta misma solicitud.',
  'Confirming this machine': 'Confirmando esta máquina',
  'We are securely recording where and when you opened the refund form.': 'Estamos registrando de forma segura dónde y cuándo abrió el formulario de reembolso.',
  'Machine confirmed': 'Máquina confirmada',
  'QR verified': 'QR verificado',
  'We saved the server time as': 'Guardamos la hora del servidor como',
  '. You will still enter the approximate purchase time below.': '. A continuación, indique la hora aproximada de compra.',
  "This machine's refund code is not available.": 'El código de reembolso de esta máquina no está disponible.',
  'Scan the machine refund code again or use the regular refund form.': 'Escanee de nuevo el código de la máquina o use el formulario normal de reembolso.',
  'This refund form is not open for customer submissions yet.': 'Este formulario aún no está disponible para solicitudes de clientes.',
  'This QR session needs to be restarted.': 'Debe reiniciar esta sesión QR.',
  'Start new QR session': 'Iniciar nueva sesión QR',
  'Use regular refund form': 'Usar el formulario normal de reembolso',
  'Your form is still here. Start a new QR session, then submit it again. You can also switch to the regular form.': 'Su formulario sigue aquí. Inicie una nueva sesión QR y vuelva a enviarlo. También puede usar el formulario normal.',
  'The code may have been replaced or disabled. You can still submit a request using the regular form and choose the machine yourself.': 'El código puede haber sido sustituido o desactivado. Puede enviar una solicitud con el formulario normal y elegir la máquina.',
  'Please reply in the same email conversation with the machine location or a description of the machine. You do not need to open another form.': 'Responda en la misma conversación por correo con la ubicación o una descripción de la máquina. No necesita abrir otro formulario.',
  'Please reply in the same email conversation so our team can continue without creating a second request.': 'Responda en la misma conversación por correo para que podamos continuar sin crear otra solicitud.',
  'We could not load the Bloomjoy machine list right now. Please reply in the same email conversation with the machine location or a description of the machine, and our team will continue from there. You do not need to complete a second form.': 'No pudimos cargar la lista de máquinas Bloomjoy. Responda en la misma conversación con la ubicación o una descripción de la máquina y continuaremos desde allí. No necesita otro formulario.',
  'We could not load the Bloomjoy machine list right now. Please try this page again shortly. If it still does not load,': 'No pudimos cargar la lista de máquinas Bloomjoy. Vuelva a intentar en unos minutos. Si sigue sin cargar,',
  '. We will help you return to this Bloomjoy form. Sending an email does not submit a refund request.': '. Le ayudaremos a volver a este formulario Bloomjoy. Enviar un correo no envía una solicitud de reembolso.',
  'DEMO DATA - visual review only. This form uses synthetic locations and redirects to a demo thank-you page instead of creating a real refund case.': 'DATOS DE DEMOSTRACIÓN: solo revisión visual. Este formulario usa ubicaciones ficticias y abre una confirmación de prueba sin crear una solicitud real.',
  'DEMO DATA — visual review only. No case or refund was read or changed.': 'DATOS DE DEMOSTRACIÓN: solo revisión visual. No se consultó ni modificó ninguna solicitud ni reembolso.',
  'Demo mode did not create a real refund case.': 'La demostración no creó una solicitud real.',
  'Most requests are reviewed within 5 business days. We’ll email you with an update.': 'La mayoría de las solicitudes se revisan en 5 días hábiles. Le enviaremos novedades por correo.',
  'We’ll find your payment and send it to our team for a refund decision. Most requests are reviewed within 5 business days.': 'Buscaremos su pago y lo enviaremos a nuestro equipo para decidir sobre el reembolso. La mayoría de las solicitudes se revisan en 5 días hábiles.',
  'Use the location’s local time. An estimate is okay.': 'Use la hora local de la ubicación. Puede dar una estimación.',
  'Details received': 'Datos recibidos',
  'We automatically re-checked your purchase.': 'Volvimos a revisar su compra automáticamente.',
  'We found one high-confidence transaction. The machine manager has been notified and can now make the refund decision.': 'Encontramos una transacción con alta confianza. Se avisó al gerente de la máquina para que decida sobre el reembolso.',
  'We still could not identify one transaction with enough confidence. Your request is now ready for the alternative resolution route.': 'Aún no pudimos identificar una transacción con suficiente confianza. Su solicitud está lista para una resolución alternativa.',
  'Your corrected details are saved. Our system will retry the transaction check without asking the machine manager to investigate your card details.': 'Sus datos corregidos están guardados. El sistema volverá a buscar la transacción sin pedir al gerente que investigue los datos de su tarjeta.',
  'You do not need to submit another form. We will email you when the refund request is resolved.': 'No necesita enviar otro formulario. Le enviaremos un correo cuando se resuelva su solicitud.',
  'Enter the four digits shown for the card inside your mobile wallet.': 'Indique los cuatro dígitos de la tarjeta que aparecen en su billetera móvil.',
  'Choose the card type shown inside your mobile wallet.': 'Elija el tipo de tarjeta que aparece en su billetera móvil.',
  'Enter your approximate purchase date and time.': 'Indique la fecha y hora aproximadas de compra.',
  'Unable to save the corrected wallet details.': 'No se pudieron guardar los datos corregidos de la billetera.',
  'This secure link is no longer available.': 'Este enlace seguro ya no está disponible.',
  'It may have expired or already been used. Reply to the Bloomjoy refund email so we can continue helping with your existing request.': 'Puede haber vencido o ya haberse usado. Responda al correo de Bloomjoy para que podamos seguir ayudándole con su solicitud existente.',
  'Opening your secure wallet-detail form…': 'Abriendo su formulario seguro de datos de billetera…',
  'Virtual last 4 shown in your wallet': 'Últimos 4 dígitos virtuales de su billetera',
  'Check the card details shown inside your mobile wallet.': 'Revise los datos de la tarjeta que aparecen en su billetera móvil.',
  'Apple Pay and Google Pay may use a virtual card number that is different from your physical card. These details give our system another chance to find the correct purchase automatically.': 'Apple Pay y Google Pay pueden usar un número virtual distinto de su tarjeta física. Estos datos ayudan al sistema a encontrar la compra correcta automáticamente.',
  'Virtual card last 4': 'Últimos 4 dígitos de la tarjeta virtual',
  'Enter only the virtual card’s last four digits. We will never ask for the full card number, security code, expiration date, wallet password, or a screenshot.': 'Indique solo los últimos cuatro dígitos de la tarjeta virtual. Nunca pediremos el número completo, código de seguridad, vencimiento, contraseña de la billetera ni una captura de pantalla.',
  'In Apple Wallet, open the card and view Card Number. Use the last four of the Apple Pay number—not the physical card.': 'En Apple Wallet, abra la tarjeta y consulte Número de tarjeta. Use los últimos cuatro dígitos del número de Apple Pay, no los de la tarjeta física.',
  'Use the logo on the card shown inside your wallet. Never send a full card number, expiration date, security code, wallet password, or screenshot.': 'Use el logotipo de la tarjeta que aparece en su billetera. Nunca envíe el número completo, vencimiento, código de seguridad, contraseña ni una captura de pantalla.',
  'Mobile wallet used': 'Billetera móvil usada',
  'Purchase amount': 'Importe de compra',
  'Purchase time': 'Hora de compra',
  'Machine': 'Máquina',
  'Location': 'Ubicación',
  'I confirm the purchase amount was': 'Confirmo que el importe de compra fue',
  'Checking transactions…': 'Buscando transacciones…',
  'Save and check my purchase': 'Guardar y revisar mi compra',
  'Request a refund': 'Solicitar un reembolso',
  'Purchase': 'Compra',
  'Where and when did you make the purchase?': '¿Dónde y cuándo hizo la compra?',
  'Machine location': 'Ubicación de la máquina',
  'Choose a location': 'Elija una ubicación',
  'Loading locations...': 'Cargando ubicaciones…',
  'Refund form is not open yet': 'El formulario de reembolso aún no está disponible',
  'Email': 'Correo electrónico',
  'We use this only for this request and its secure status link.': 'Lo usamos solo para esta solicitud y su enlace seguro de seguimiento.',
  'Purchase date': 'Fecha de compra',
  'Approximate purchase time': 'Hora aproximada de compra',
  'Payment': 'Pago',
  'How did you pay?': '¿Cómo pagó?',
  'Card': 'Tarjeta',
  'Cash': 'Efectivo',
  'Amount paid': 'Importe pagado',
  'Example: 12.00': 'Ejemplo: 12.00',
  'How can we make it right?': '¿Cómo podemos ayudarle?',
  'Bloomjoy gift card': 'Tarjeta de regalo de Bloomjoy',
  'Recommended': 'Recomendado',
  'Usually emailed within a few hours.': 'Normalmente se envía por correo en unas horas.',
  'Refund to my original card payment': 'Reembolso a mi tarjeta original',
  'We investigate the purchase and request your refund from the payment processor, so this takes longer.': 'Revisamos la compra y solicitamos el reembolso al procesador de pagos, por lo que tarda más.',
  'We investigate the purchase and request your refund from the payment processor, so this takes longer. Most requests are reviewed within 5 business days.': 'Revisamos la compra y solicitamos el reembolso al procesador de pagos, por lo que tarda más. La mayoría de las solicitudes se revisan en 5 días hábiles.',
  'Loading your gift card value and terms…': 'Cargando el valor y las condiciones de su tarjeta de regalo…',
  'Choose the machine and enter your purchase amount to see your gift card value and terms.': 'Elija la máquina e indique el importe de compra para ver el valor y las condiciones de la tarjeta de regalo.',
  'Submitting accepts this gift card and its terms. One automatic gift card per email in 12 months; repeat requests are reviewed by our team.': 'Al enviar, acepta esta tarjeta de regalo y sus condiciones. Una tarjeta automática por correo cada 12 meses; nuestro equipo revisa las solicitudes repetidas.',
  'We could not load a gift card offer for this purchase right now. Please try again, or contact us using the same email conversation.': 'No pudimos cargar la oferta de tarjeta de regalo. Inténtelo de nuevo o contáctenos en la misma conversación por correo.',
  'Try loading the offer again': 'Volver a cargar la oferta',
  'What happened': 'Qué sucedió',
  'Tell us what went wrong with the purchase.': 'Cuéntenos qué problema tuvo con la compra.',
  'What best describes the problem?': '¿Qué opción describe mejor el problema?',
  'Choose one': 'Elija una opción',
  'Charged, but no product came out': 'Se cobró, pero no salió el producto',
  'Paid, but no product came out': 'Pagué, pero no salió el producto',
  'The product came out incorrectly': 'El producto salió mal',
  'Charged more than once': 'Se cobró más de una vez',
  'Paid more than once': 'Pagué más de una vez',
  'Charged the wrong amount': 'Se cobró un importe incorrecto',
  'Machine took the wrong amount': 'La máquina tomó un importe incorrecto',
  'Received fewer items than I paid for': 'Recibí menos productos de los que pagué',
  'Expected change from a cash payment': 'Esperaba cambio al pagar en efectivo',
  'Cash inserted': 'Efectivo introducido',
  'Change you expected': 'Cambio que esperaba',
  'Purchase amount (cost of the items)': 'Importe de compra (precio de los productos)',
  'Enter the cost of the items here. Enter the bill you inserted below.': 'Indique aquí el precio de los productos. Abajo indique el efectivo que introdujo.',
  'Our machines do not provide change. Our team will review your request for a courtesy gift card.': 'Nuestras máquinas no dan cambio. Nuestro equipo revisará su solicitud de una tarjeta de regalo de cortesía.',
  'Tell us how many items you paid for and how many you received in the optional details below.': 'En los detalles opcionales, indique cuántos productos pagó y cuántos recibió.',
  'Your request will be reviewed by a manager. We will email you when the review is complete.': 'Un gerente revisará su solicitud. Le enviaremos un correo cuando termine la revisión.',
  'Proposed gift card. A manager will review the amount before it is issued.': 'Tarjeta de regalo propuesta. Un gerente revisará el importe antes de emitirla.',
  'Submitting accepts the gift card terms. The final amount depends on manager review.': 'Al enviar, acepta las condiciones de la tarjeta de regalo. El importe final depende de la revisión del gerente.',
  'Send request for review': 'Enviar solicitud para revisión',
  'Enter the cash you inserted.': 'Indique el efectivo que introdujo.',
  'Enter the change you expected.': 'Indique el cambio que esperaba.',
  'Expected change must be less than the cash inserted.': 'El cambio esperado debe ser menor que el efectivo introducido.',
  'Something else': 'Otro problema',
  'Add optional details': 'Agregar detalles opcionales',
  'These can help with unusual purchases. You can submit your request without them.': 'Pueden ayudarnos con compras inusuales. Puede enviar su solicitud sin estos detalles.',
  'Name (optional)': 'Nombre (opcional)',
  'Phone (optional)': 'Teléfono (opcional)',
  'How close is the time? (optional)': '¿Qué tan precisa es la hora? (opcional)',
  'Just a rough estimate': 'Solo una estimación aproximada',
  'Exact or within a few minutes': 'Exacta o con unos minutos de diferencia',
  'Within about 15 minutes': 'Con unos 15 minutos de diferencia',
  'Within about 1 hour': 'Con aproximadamente 1 hora de diferencia',
  'How did you find the time? (optional)': '¿Cómo encontró la hora? (opcional)',
  'Choose if known': 'Elija si lo sabe',
  'Purchase alert or receipt': 'Aviso de compra o recibo',
  'From memory': 'De memoria',
  'I am not sure': 'No estoy seguro/a',
  'A bank posting time can differ from when you used the machine.': 'La hora registrada por el banco puede ser distinta de cuando usó la máquina.',
  'Anything else? (optional)': '¿Algo más? (opcional)',
  'For example, whether anything came out or what the screen showed.': 'Por ejemplo, si salió algún producto o qué mostró la pantalla.',
  'Your request goes to the manager responsible for that machine.': 'Su solicitud se envía al gerente responsable de esa máquina.',
  'Sending your request...': 'Enviando su solicitud…',
  'Accept gift card & send request': 'Aceptar tarjeta de regalo y enviar solicitud',
  'Send refund request': 'Enviar solicitud de reembolso',
  'We could not confirm your request.': 'No pudimos confirmar su solicitud.',
  'Choose the Bloomjoy machine you used.': 'Elija la máquina Bloomjoy que usó.',
  'Choose the machine you used.': 'Elija la máquina que usó.',
  'Enter a valid email address.': 'Indique un correo electrónico válido.',
  'Enter the purchase date.': 'Indique la fecha de compra.',
  'Enter the approximate purchase time.': 'Indique la hora aproximada de compra.',
  'Enter the amount you paid.': 'Indique el importe que pagó.',
  'Choose the option that best describes the problem.': 'Elija la opción que mejor describe el problema.',
  'Please check the highlighted fields.': 'Revise los campos resaltados.',
  'Please wait for your gift card terms to load, then try again.': 'Espere a que carguen las condiciones de su tarjeta de regalo e inténtelo de nuevo.',
  'Unable to submit refund request.': 'No se pudo enviar la solicitud de reembolso.',
  'Your answers are still here. Try again to safely continue this same submission, even after refreshing this page.': 'Sus respuestas siguen aquí. Inténtelo de nuevo para continuar con esta misma solicitud, incluso después de actualizar la página.',
  'Your answers are still here. Try again without refreshing this page so we can safely continue this same submission.': 'Sus respuestas siguen aquí. Inténtelo de nuevo sin actualizar la página para continuar con esta misma solicitud.',
  'Tell us about one purchase so our team can review your request.': 'Cuéntenos sobre una compra para que nuestro equipo revise su solicitud.',
  'Let’s make your next visit a little sweeter. Tell us about one purchase and choose a Bloomjoy gift card, or an original-payment refund for a card purchase.': 'Hagamos su próxima visita un poco más dulce. Cuéntenos sobre una compra y elija una tarjeta de regalo Bloomjoy o, si pagó con tarjeta, un reembolso al pago original.',
  'Cash purchases receive a Bloomjoy gift card. For card purchases, you can choose a gift card or a refund to your original payment.': 'Las compras en efectivo reciben una tarjeta de regalo Bloomjoy. Si pagó con tarjeta, puede elegir una tarjeta de regalo o un reembolso al pago original.',
  'Tell us how you paid. Our team will review your request.': 'Indique cómo pagó. Nuestro equipo revisará su solicitud.',
  'Gift card or original-payment refund.': 'Tarjeta de regalo o reembolso al pago original.',
  'Refund to your original card payment.': 'Reembolso a la tarjeta con la que pagó.',
  'Bloomjoy gift card. No payment details needed.': 'Tarjeta de regalo Bloomjoy. No necesita datos de pago.',
  'Cash purchase. No card details needed.': 'Compra en efectivo. No necesita datos de tarjeta.',
  'Which machine did you use?': '¿Qué máquina usó?',
  'Choose the machine label': 'Elija la etiqueta de la máquina',
  'Look for the small TT label on the machine.': 'Busque la pequeña etiqueta TT en la máquina.',
  'Resolution': 'Resolución',
  'Last 4 digits shown for this payment': 'Últimos 4 dígitos de este pago',
  'Enter only the last 4 digits shown for this payment.': 'Indique solo los últimos 4 dígitos de este pago.',
  'Enter only 4 digits—never a full card number, security code, or screenshot.': 'Indique solo 4 dígitos; nunca el número completo, el código de seguridad ni una captura de pantalla.',
  'I used Apple Pay or another phone/watch wallet': 'Usé Apple Pay u otra billetera del teléfono o reloj',
  'Wallet (optional)': 'Billetera (opcional)',
  'Device used (optional)': 'Dispositivo usado (opcional)',
  'Phone': 'Teléfono',
  'Watch': 'Reloj',
  'Another mobile wallet': 'Otra billetera móvil',
  'Another wallet': 'Otra billetera',
  'How did you use the card? (optional)': '¿Cómo usó la tarjeta? (opcional)',
  'Not sure': 'No estoy seguro/a',
  'Tapped the card': 'Acerqué la tarjeta',
  'Inserted the card': 'Introduje la tarjeta',
  'Swiped the card': 'Deslicé la tarjeta',
  'Inserted or swiped — not sure which': 'La introduje o deslicé; no recuerdo cuál',
  'Card type (optional)': 'Tipo de tarjeta (opcional)',
  'Card type': 'Tipo de tarjeta',
  'Other / Not sure': 'Otro / No estoy seguro/a',
  'Where did you find the last 4? (optional)': '¿Dónde encontró los últimos 4 dígitos? (opcional)',
  'Physical card': 'Tarjeta física',
  'Card shown for the wallet or device': 'Tarjeta que aparece en la billetera o dispositivo',
  'Bank record or purchase alert': 'Registro bancario o aviso de compra',
  'Open the card details in Apple Pay or your wallet on the exact phone or watch you used. A phone and watch can show different last 4 digits for the same physical card. Use the virtual last 4 shown for this wallet payment. Do not use the last 4 printed on the physical card.': 'Abra los datos de la tarjeta en Apple Pay o su billetera en el teléfono o reloj que usó. El teléfono y el reloj pueden mostrar distintos últimos 4 dígitos para la misma tarjeta física. Use los últimos 4 dígitos virtuales de este pago, no los impresos en la tarjeta.',
  'Request received': 'Solicitud recibida',
  'A sweeter visit starts here.': 'Una visita más dulce empieza aquí.',
  'We received your refund request.': 'Recibimos su solicitud de reembolso.',
  'Thanks for letting us make it right. We have your gift card request and will email you with the next update.': 'Gracias por dejarnos ayudarle. Recibimos su solicitud de tarjeta de regalo y le enviaremos novedades por correo.',
  'We are sorry the machine did not work as expected. Most requests are reviewed within 5 business days, and we will email you if we need one specific detail.': 'Lamentamos que la máquina no funcionara como esperaba. La mayoría de las solicitudes se revisan en 5 días hábiles. Le escribiremos si necesitamos algún dato.',
  'Reference': 'Referencia',
  'Reference:': 'Referencia:',
  'Sent by email': 'Enviada por correo',
  'Keep this reference handy. You do not need to submit another form for this purchase.': 'Guarde esta referencia. No necesita enviar otro formulario por esta compra.',
  'Your gift card request is saved. Gift cards are usually emailed within a few hours. If review or delivery takes longer, your status page will keep you updated.': 'Su solicitud de tarjeta de regalo está guardada. Normalmente las tarjetas se envían en unas horas. Si la revisión o el envío tarda más, encontrará novedades en su página de seguimiento.',
  'A manager will review the cash purchase details before deciding what happens next.': 'Un gerente revisará los datos de la compra en efectivo antes de decidir el siguiente paso.',
  "We will review the card payment against the machine's payment records before a manager makes a separate refund decision.": 'Compararemos el pago con los registros de la máquina antes de que un gerente decida sobre el reembolso.',
  'A manager will review the purchase details before deciding what happens next.': 'Un gerente revisará los datos de compra antes de decidir el siguiente paso.',
  'Check refund status': 'Ver estado del reembolso',
  'Back to Bloomjoy': 'Volver a Bloomjoy',
  'Report a different purchase': 'Informar otra compra',
  'Secure refund status': 'Estado seguro del reembolso',
  'Checking your request': 'Consultando su solicitud',
  'This page is read-only. It cannot submit or retry a refund.': 'Esta página solo muestra información. No puede enviar ni volver a intentar un reembolso.',
  'This secure link is not available': 'Este enlace seguro no está disponible',
  'The link may be incomplete or no longer active. This does not create a new request or change an existing refund.': 'El enlace puede estar incompleto o ya no estar activo. Esto no crea una nueva solicitud ni cambia un reembolso existente.',
  'Reply to your Bloomjoy refund email or contact customer service with your reference. You do not need to submit another form.': 'Responda al correo de Bloomjoy sobre su reembolso o contacte a atención al cliente con su referencia. No necesita otro formulario.',
  'Email Bloomjoy customer service': 'Escribir a atención al cliente de Bloomjoy',
  'email Bloomjoy customer service': 'escriba a atención al cliente de Bloomjoy',
  'Current status': 'Estado actual',
  'Review complete': 'Revisión terminada',
  'No refund was issued. Reply to your Bloomjoy email if you want us to review the same request again.': 'No se emitió un reembolso. Responda al correo de Bloomjoy si desea que revisemos la misma solicitud de nuevo.',
  'Refund progress': 'Avance del reembolso',
  'Received': 'Recibido',
  'Reviewing': 'En revisión',
  'Initiated': 'Iniciado',
  'Confirming': 'Confirmando',
  'Confirmed': 'Confirmado',
  'What happens next': 'Qué sigue',
  'Last updated': 'Última actualización',
  'Checking for updates…': 'Buscando novedades…',
  'Updates automatically': 'Se actualiza automáticamente',
  'For your privacy, this page does not show card digits, payment-provider details, or internal review notes.': 'Para proteger su privacidad, esta página no muestra dígitos de tarjeta, datos del proveedor de pagos ni notas internas.',
  'Your request is being reviewed': 'Su solicitud está en revisión',
  'Our team is reviewing your gift card request. Your answers are saved.': 'Nuestro equipo está revisando su solicitud de tarjeta de regalo. Sus respuestas están guardadas.',
  'We will email you when the review is complete. You do not need to submit again.': 'Le enviaremos un correo cuando termine la revisión. No necesita volver a enviar la solicitud.',
  'We’re preparing your gift card': 'Estamos preparando su tarjeta de regalo',
  'Your request is saved. Your gift card is not ready yet.': 'Su solicitud está guardada. Su tarjeta de regalo aún no está lista.',
  'We will email your code once it is ready. There is nothing else you need to do.': 'Le enviaremos el código cuando esté listo. No necesita hacer nada más.',
  'Your review is complete': 'Su revisión ha terminado',
  'A gift card was not issued for this request.': 'No se emitió una tarjeta de regalo para esta solicitud.',
  'Reply to your Bloomjoy email if you would like us to review the same request again.': 'Responda al correo de Bloomjoy si desea que revisemos la misma solicitud de nuevo.',
  'A little sweetness is on its way': 'Un poco de dulzura está en camino',
  'Your gift card email was delivered. Use the code and instructions in that email.': 'Se entregó el correo con su tarjeta de regalo. Use el código y las instrucciones de ese correo.',
  'We have sent your gift card email. Check your inbox or spam folder. Reply to your Bloomjoy email if you need a hand.': 'Enviamos el correo con su tarjeta de regalo. Revise su bandeja de entrada o correo no deseado. Responda al correo de Bloomjoy si necesita ayuda.',
  'Your gift card is saved, but its email delivery needs attention. Our team is working on it. You do not need to submit again.': 'Su tarjeta de regalo está guardada, pero hubo un problema con el correo. Nuestro equipo está trabajando en ello. No necesita otra solicitud.',
  'We’re sending your gift card email. Your code and instructions will be in that email.': 'Estamos enviando el correo con su tarjeta de regalo. Incluye el código y las instrucciones.',
} as const;

export type RefundCopyKey = keyof typeof refundSpanishCopy;
const englishForSpanish = new Map<string, string>(Object.entries(refundSpanishCopy).map(([english, spanish]) => [spanish, english]));
export function refundCustomerText(text: string, locale: RefundCustomerLocale): string {
  const english = englishForSpanish.get(text) ?? text;
  return locale === 'es' && english in refundSpanishCopy
    ? refundSpanishCopy[english as RefundCopyKey] : english;
}
