export type SalesReportPdfRow = {
  period_start?: string;
  periodStart?: string;
  machine_label?: string;
  machineLabel?: string;
  location_name?: string;
  locationName?: string;
  payment_method?: string;
  paymentMethod?: string;
  net_sales_cents?: number;
  netSalesCents?: number;
  refund_amount_cents?: number;
  refundAmountCents?: number;
  gross_sales_cents?: number;
  grossSalesCents?: number;
  transaction_count?: number;
  transactionCount?: number;
};

export type SalesReportPdfSummary = {
  netSalesCents: number;
  refundAmountCents: number;
  grossSalesCents: number;
  transactionCount: number;
};

const encoder = new TextEncoder();

const toAscii = (value: unknown): string =>
  String(value ?? "")
    .normalize("NFKD")
    .replace(/[^\x20-\x7e]/g, "")
    .replace(/\s+/g, " ")
    .trim();

const escapePdfText = (value: string): string =>
  toAscii(value).replace(/\\/g, "\\\\").replace(/\(/g, "\\(").replace(/\)/g, "\\)");

const pad = (value: string, length: number): string => {
  const normalized = toAscii(value);
  if (normalized.length >= length) {
    return normalized.slice(0, length - 1);
  }
  return normalized.padEnd(length, " ");
};

const formatCurrency = (cents: number): string =>
  `$${(Math.round(Number(cents || 0)) / 100).toLocaleString("en-US", {
    minimumFractionDigits: 2,
    maximumFractionDigits: 2,
  })}`;

const numberValue = (value: unknown): number => {
  const normalized = Number(value ?? 0);
  return Number.isFinite(normalized) ? normalized : 0;
};

export const summarizeSalesReportPdfRows = (
  rows: SalesReportPdfRow[]
): SalesReportPdfSummary =>
  rows.reduce<SalesReportPdfSummary>(
    (summary, row) => ({
      netSalesCents:
        summary.netSalesCents + numberValue(row.net_sales_cents ?? row.netSalesCents),
      refundAmountCents:
        summary.refundAmountCents +
        numberValue(row.refund_amount_cents ?? row.refundAmountCents),
      grossSalesCents:
        summary.grossSalesCents +
        numberValue(row.gross_sales_cents ?? row.grossSalesCents),
      transactionCount:
        summary.transactionCount +
        numberValue(row.transaction_count ?? row.transactionCount),
    }),
    {
      netSalesCents: 0,
      refundAmountCents: 0,
      grossSalesCents: 0,
      transactionCount: 0,
    }
  );

const buildReportLines = ({
  title,
  subtitle,
  rows,
  summary,
}: {
  title: string;
  subtitle: string;
  rows: SalesReportPdfRow[];
  summary: SalesReportPdfSummary;
}): string[] => {
  const lines = [
    title,
    subtitle,
    "",
    `Net sales: ${formatCurrency(summary.netSalesCents)}    Refunds: ${formatCurrency(
      summary.refundAmountCents
    )}    Gross sales: ${formatCurrency(summary.grossSalesCents)}    Transactions: ${
      summary.transactionCount
    }`,
    "",
    `${pad("Period", 12)} ${pad("Machine", 24)} ${pad("Payment", 8)} ${pad(
      "Net",
      13
    )} ${pad("Refunds", 13)} ${pad("Gross", 13)} Txns`,
    `${"-".repeat(12)} ${"-".repeat(24)} ${"-".repeat(8)} ${"-".repeat(13)} ${"-".repeat(
      13
    )} ${"-".repeat(13)} ${"-".repeat(5)}`,
  ];

  rows.slice(0, 44).forEach((row) => {
    const period = toAscii(row.period_start ?? row.periodStart);
    const machine = toAscii(row.machine_label ?? row.machineLabel);
    const payment = toAscii(row.payment_method ?? row.paymentMethod);
    const netSales = formatCurrency(numberValue(row.net_sales_cents ?? row.netSalesCents));
    const refunds = formatCurrency(
      numberValue(row.refund_amount_cents ?? row.refundAmountCents)
    );
    const gross = formatCurrency(numberValue(row.gross_sales_cents ?? row.grossSalesCents));
    const transactions = String(numberValue(row.transaction_count ?? row.transactionCount));

    lines.push(
      `${pad(period, 12)} ${pad(machine, 24)} ${pad(payment, 8)} ${pad(
        netSales,
        13
      )} ${pad(refunds, 13)} ${pad(gross, 13)} ${transactions}`
    );
  });

  if (rows.length > 44) {
    lines.push("");
    lines.push(`${rows.length - 44} additional rows omitted from this PDF preview.`);
  }

  return lines;
};

export const buildSalesReportPdf = ({
  title,
  subtitle,
  rows,
  summary,
}: {
  title: string;
  subtitle: string;
  rows: SalesReportPdfRow[];
  summary?: SalesReportPdfSummary;
}): Uint8Array => {
  const finalSummary = summary ?? summarizeSalesReportPdfRows(rows);
  const lines = buildReportLines({
    title: toAscii(title || "Bloomjoy sales report"),
    subtitle: toAscii(subtitle || "Generated by Bloomjoy Hub"),
    rows,
    summary: finalSummary,
  });
  const textCommands = lines
    .slice(0, 58)
    .map((line, index) => {
      const fontCommand = index === 0 ? "/F1 15 Tf\n" : index === 1 ? "/F1 9 Tf\n" : "";
      const offsetCommand = index === 0 ? "50 752 Td\n" : "0 -12 Td\n";
      return `${fontCommand}${offsetCommand}(${escapePdfText(line)}) Tj`;
    })
    .join("\n");
  const content = `BT\n${textCommands}\nET`;
  const contentLength = encoder.encode(content).length;

  const objects = [
    "<< /Type /Catalog /Pages 2 0 R >>",
    "<< /Type /Pages /Kids [3 0 R] /Count 1 >>",
    "<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Resources << /Font << /F1 4 0 R >> >> /Contents 5 0 R >>",
    "<< /Type /Font /Subtype /Type1 /BaseFont /Courier >>",
    `<< /Length ${contentLength} >>\nstream\n${content}\nendstream`,
  ];

  let pdf = "%PDF-1.4\n";
  const offsets: number[] = [];
  objects.forEach((object, index) => {
    offsets.push(encoder.encode(pdf).length);
    pdf += `${index + 1} 0 obj\n${object}\nendobj\n`;
  });

  const xrefOffset = encoder.encode(pdf).length;
  pdf += `xref\n0 ${objects.length + 1}\n0000000000 65535 f \n`;
  offsets.forEach((offset) => {
    pdf += `${String(offset).padStart(10, "0")} 00000 n \n`;
  });
  pdf += `trailer\n<< /Size ${objects.length + 1} /Root 1 0 R >>\nstartxref\n${xrefOffset}\n%%EOF`;

  return encoder.encode(pdf);
};
